version: '3.1'
services:
  stats-server:
    build: stats-service/server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=practicum
      - SPRING_DATASOURCE_PASSWORD=practicum

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "1234:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=practicum
      - POSTGRES_PASSWORD=practicum

  ewm-service:
    build: ewm-service
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_SERVICE_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=practicum
      - SPRING_DATASOURCE_PASSWORD=practicum

  ewm-db:
    image: postgres:14-alpine
    container_name: ewn-db-container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=practicum
      - POSTGRES_PASSWORD=practicum