--drop table hits cascade;

create TABLE IF NOT EXISTS hits
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255),
    uri VARCHAR(255),
    ip VARCHAR(50),
    timestamp timestamp WITHOUT TIME ZONE
);